image: docker:latest

stages:
    - build
    - push

variables:
    DOCKER_BUILDKIT: 1
    APP_IMAGE: "${CI_REGISTRY_IMAGE}/app"
    APP_TMP_IMAGE: "${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_SHORT_SHA}"

services:
    - docker:dind

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

publiccode:
    stage: build
    allow_failure: true
    script:
      - docker run -i italia/publiccode-parser-go /dev/stdin < publiccode.yml

tmp_build_app:
    stage: build
    script:
        - docker pull $APP_IMAGE:latest || true
        - docker pull  $APP_TMP_IMAGE || docker build --build-arg CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME --build-arg CI_COMMIT_TAG=$CI_COMMIT_TAG --build-arg CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA --pull -t $APP_TMP_IMAGE -f Dockerfile .
        - docker push  $APP_TMP_IMAGE
    only:
        - branches
        - tags

push_app_branches:
    stage: push
    script:
        - docker pull  $APP_TMP_IMAGE
        - docker tag   $APP_TMP_IMAGE "$APP_IMAGE:$CI_COMMIT_REF_NAME"
        - docker push "$APP_IMAGE:$CI_COMMIT_REF_NAME"
    only:
        - branches
    except:
        - master

push_app_tags:
    stage: push
    script:
        - docker pull  $APP_TMP_IMAGE
        - docker tag   $APP_TMP_IMAGE "$APP_IMAGE:$CI_COMMIT_TAG"
        - docker push "$APP_IMAGE:$CI_COMMIT_TAG"
    only:
        - tags

push_app_latest:
    stage: push
    script:
        - docker pull  $APP_TMP_IMAGE
        - docker tag   $APP_TMP_IMAGE "$APP_IMAGE:latest"
        - docker push "$APP_IMAGE:latest"
    only:
        - master

# vim: set noet sw=4 ts=4:
