gitlab:
  release: false
git:
  tagname: "${version}"
  changelog: "./changelog.sh ${latestTag} ${version} " 
  push: false
  requireCleanWorkingDir: false
  requireUpstream: false
hooks:
  "after:bump": "./changelog.sh ${latestVersion} ${version} >> CHANGELOG.md"
  "after:git:release": "echo After git push, before github release"
  "after:release": "echo Successfully released ${name} version ${version} to ${repo.repository}."

