gitlab:
  release: true 
  releaseNotes: "./changelog.sh ${latestTag} ${version} " 
git:
  tagname: "${version}"
  push: true 
  requireCleanWorkingDir: true
hooks:
  "after:bump": "./changelog.sh ${latestVersion} ${version} >> CHANGELOG.md"
  "after:git:release": "echo After git push, before github release"
  "after:release": "echo Successfully released ${name} version ${version} to ${repo.repository}."

