version: "3.7"

services:
    
    php:
        build:
            context: .
            
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
            args:
                php_image: registry.gitlab.com/opencontent/opencity/php:latest
    
    pgweb:
        image: sosedoff/pgweb
        environment:
            DATABASE_URL: postgres://openpa:openp4ssword@postgres:5432/opencity?sslmode=disable
        depends_on:
            - postgres
    
    solr:
        build:
            context: .
            dockerfile: Dockerfile.solr
        environment:
            VERBOSE: 'yes'
        ports:
            - 8983:8983

    varnish:
        build:
            context: .
            dockerfile: Dockerfile.varnish