name: 'Gestione Area riservata'
policies:
    -
        ModuleName: content
        FunctionName: create
        Limitation:
            Class:
                - classid(document)
            ParentClass:
                - classid(restriced_area)
    -
        ModuleName: content
        FunctionName: read
        Limitation:
            Class:
                - classid(document)
                - classid(restriced_area)
                - classid(user)
                - classid(employee)
                - classid(politico)
    -
        ModuleName: content
        FunctionName: remove
        Limitation:
            Owner:
                - '1'
    -
        ModuleName: content
        FunctionName: edit
        Limitation:
            Class:
                - classid(restriced_area)
    -
        ModuleName: content
        FunctionName: create
        Limitation:
            Subtree:
                - $content_Aree-riservate_path_string
            Class:
                - classid(restriced_area)
            ParentClass:
                - classid(folder)
    -
        ModuleName: section
        FunctionName: assign
        Limitation:
            Class:
                - classid(restriced_area)