name: "Editor backend (import csv)"
policies:
    -
        ModuleName: csvimport
        FunctionName: '*'
        Limitation: {}
    -
        ModuleName: sqliimport
        FunctionName: '*'
        Limitation: {}
    -
        ModuleName: user
        FunctionName: login
        Limitation:
            SiteAccess:
                - ezcrc32($identifier_backend)
                - ezcrc32(backend)