name: Members
policies:
    -
        ModuleName: user
        FunctionName: password
        Limitation: {  }
    -
        ModuleName: user
        FunctionName: selfedit
        Limitation: {  }

    -
        ModuleName: ezjscore
        FunctionName: call
        Limitation:
            FunctionList:
                - ezstarrating_user_has_rated
    -
        ModuleName: user
        FunctionName: login
        Limitation:
            SiteAccess:
                - ezcrc32($identifier_frontend)
                - ezcrc32(frontend)