rootNodeIdList:
    article: '$contenttree_OpenCity_Novita_node'
    document: '$contenttree_OpenCity_Documenti-e-dati_node'
dataTimeAttributeIdentifierList:
    article: dead_line
    document: publication_end_time
sectionIdList:
    article: restricted
    document: restricted
secondsExpire: []
overrideValue: false
ignore: false
