ruleDefinitions:
    set_public_by_published:
        CurrentState: privacy.private
        DestinationState: privacy.public
        Conditions:
            - published;lt;NOW
    set_public_by_publication_start_time:
        CurrentState: privacy.private
        DestinationState: privacy.public
        Conditions:
            - publication_start_time;lt;NOW
    set_concorso_in_atto_by_data_di_scadenza_delle_iscrizioni:
        CurrentState: concorso.nuovo
        DestinationState: concorso.in_atto
        Conditions:
            - data_di_scadenza_delle_iscrizioni;lt;NOW
    set_concorso_concluso_by_data_di_conclusione_del_concorso:
        CurrentState: concorso.in_atto
        DestinationState: concorso.concluso
        Conditions:
            - data_di_conclusione;lt;NOW
    set_concorso_concluso_by_data_di_conclusione_del_concorso_from_nuovo:
        CurrentState: concorso.nuovo
        DestinationState: concorso.concluso
        Conditions:
            - data_di_conclusione;lt;NOW
    set_private_by_dead_line:
        CurrentState: privacy.public
        DestinationState: privacy.private
        Conditions:
            - dead_line;lt;NOW
ruleApplications:
    article:
        - set_public_by_published
        - set_private_by_dead_line
    document:
        - set_public_by_publication_start_time
        - set_concorso_in_atto_by_data_di_scadenza_delle_iscrizioni
        - set_concorso_concluso_by_data_di_conclusione_del_concorso
        - set_concorso_concluso_by_data_di_conclusione_del_concorso_from_nuovo
