metadata:
    remoteId: 303df154b15e47f7986343c30ba57637
    classIdentifier: topic
    sectionIdentifier: standard
    languages:
        - ita-IT
data:
    ita-IT:
        name: 'Prodotti alimentari'
        managed_by_area: {  }
        managed_by_political_body: {  }
        type: null
        description: null
        eu: 'http://eurovoc.europa.eu/100257'
        theme: null
        data_themes_eurovocs: {  }
        image: {  }
        abstract: ''
        icon: null
        layout: {  }
        help: {  }
        show_topic_children: 1
sort_data:
    sort_field: 9
    sort_order: 1
    priority: 0
